lib/frontman_web/router.ex
defmodule FrontmanWeb.Router do
  use FrontmanWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :auth do
    plug Frontman.UserManager.Pipeline
    plug FrontmanWeb.Plug.AssignCurrentUser
  end

  pipeline :ensure_auth do
    plug Guardian.Plug.EnsureAuthenticated
  end

  # Maybe logged in routes
  scope "/", FrontmanWeb do
    pipe_through [:browser, :auth]

    get "/", PageController, :index

    get "/login", SessionController, :new
    post "/login", SessionController, :login
    get "/logout", SessionController, :logout
  end

  # Definitely logged in scope
  scope "/", FrontmanWeb do
    pipe_through [:browser, :auth, :ensure_auth]

    resources "/feeds", FeedController
  end

  # Public routes
  scope "/", FrontmanWeb do
    pipe_through [:browser]

    get "/f/*alias_segments", ProxyController, :show
  end
end

lib/frontman_web/templates/page/index.html.eex
<div class="mt-12 bg-white shadow p-8">
  

  <div class="flex flex-row">
    <%= if assigns[:current_user] do %>
      <%= link "/feeds", to: Routes.feed_path(@conn, :index) %>
    <% else %>
      <%= link "login", to: "/login" %>
    <% end %>
  </div>

</div>

lib/frontman_web/templates/page/protected.html.eex
<h2>Protected Page</h2>
<p>You can only see this page if you are logged in</p>
<p>You're logged in as <%= @current_user.username %></p>