lib/frontman_web/router.ex
defmodule FrontmanWeb.Router do
  use FrontmanWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :auth do
    plug Frontman.UserManager.Pipeline
    plug FrontmanWeb.Plug.AssignCurrentUser
  end

  pipeline :ensure_auth do
    plug Guardian.Plug.EnsureAuthenticated
  end

  # Maybe logged in routes
  scope "/", FrontmanWeb do
    pipe_through [:browser, :auth]

    get "/", PageController, :index

    get "/login", SessionController, :new
    post "/login", SessionController, :login
    get "/logout", SessionController, :logout
  end

  # Definitely logged in scope
  scope "/", FrontmanWeb do
    pipe_through [:browser, :auth, :ensure_auth]

    resources "/feeds", FeedController
  end

  # Public routes
  scope "/", FrontmanWeb do
    pipe_through [:browser]

    get "/f/*alias_segments", ProxyController, :show
  end
end

lib/frontman/directory/feed.ex
defmodule Frontman.Directory.Feed do
  use Ecto.Schema
  import Ecto.Changeset

  schema "feeds" do
    field :alias, :string
    field :origin_url, :string

    belongs_to :user, Frontman.UserManager.User

    timestamps()
  end

  # todo: normalise alias
  #   - strip leading and trailing slashes
  #   - only url safe characters
  #   - do something with whitespace?
  #   - make unique

  # todo: rename "alias" because it's a reserved word in Elixir

  @doc false
  def changeset(feed, attrs) do
    feed
    |> cast(attrs, [:origin_url, :alias])
    |> validate_required([:origin_url, :alias])
  end
end

lib/frontman_web/controllers/feeds_controller.ex
defmodule FrontmanWeb.FeedController do
  use FrontmanWeb, :controller

  alias Frontman.Directory
  alias Frontman.Directory.Feed

  def index(conn, _) do
    user = Guardian.Plug.current_resource(conn)
    feeds = Directory.list_feeds(user)

    render(conn, "index.html", feeds: feeds)
  end

  def new(conn, _) do
    user = Guardian.Plug.current_resource(conn)
    feed = Ecto.build_assoc(user, :feeds) |> Feed.changeset(%{})

    render(conn, "new.html", feed: feed)
  end

  def create(conn, %{"feed" => feed_params}) do
    user = Guardian.Plug.current_resource(conn)

    case Directory.create_feed(user, feed_params) do
      {:ok, _feed} ->
        conn
        |> put_flash(:info, "feed created.")
        |> redirect(to: Routes.feed_path(conn, :index))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", feed: changeset)
    end
  end
end

lib/frontman_web/views/feed_view.ex
defmodule FrontmanWeb.FeedView do
  use FrontmanWeb, :view
end

lib/frontman_web/templates/feed/index.html.eex
<div class="bg-white shadow p-8 rounded mt-8">
  <h2 class="font-bold text-2xl mb-8">Feeds</h2>

  <table class="w-full mb-4">
    <thead>
      <tr>
        <th class="p-2">Origin</th>
        <th class="p-2">Target</th>
      </tr>
    </thead>
    <tbody>
      <%= for feed <- @feeds do %>
        <tr class="bg-white odd:bg-gray-100">
          <td class="p-2">
            <%= link feed.origin_url, to: feed.origin_url, target: "_blank", class: "text-blue-600 hover:underline" %>
          </td>
          <td class="p-2">
            <%= link Routes.proxy_url(@conn, :show, String.split(feed.alias, "/")), to: Routes.proxy_url(@conn, :show, String.split(feed.alias, "/")), target: "_blank", class: "text-blue-600 hover:underline" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= link "Add Feed", to: Routes.feed_path(@conn, :new), class: "bg-blue-500 hover:bg-blue-400 text-white hover:text-white font-bold py-2 px-4 border-b-4 border-blue-700 hover:border-blue-500 rounded" %>

</div>

lib/frontman_web/templates/feed/new.html.eex
<div class="bg-white shadow p-8 rounded mt-12">

  <h2 class="font-bold text-4xl mb-8">Add Feed</h2>

  <%= form_for @feed, Routes.feed_path(@conn, :create), fn f -> %>

    <p class="mb-12">
      <%= label f, :origin_url, class: "block text-gray-700 text-sm font-bold mb-2" %>
      <%= text_input f, :origin_url, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
      <%= error_tag f, :origin_url %>
    </p>

    <p class="mb-12">
      <%= label f, :alias, class: "block text-gray-700 text-sm font-bold mb-2" %>
      <%= text_input f, :alias , class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"%>
      <%= error_tag f, :alias %>
    </p>

    <%= submit "Add Feed", class: "bg-blue-500 hover:bg-blue-400 text-white hover:text-white font-bold py-2 px-4 border-b-4 border-blue-700 hover:border-blue-500 rounded" %>

  <% end %>

</div>